if(n2==0)
throw runtime_error("cannot divide by 0");
try{
cout<<n1/n2;
}
catch(const runtime_error &e)
{
cout<<"exception caught"<<e what();
}